/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import model.Calc;

/**
 *
 * @author giuli
 */
public class Calculadora extends javax.swing.JInternalFrame {
    double num1;
    double num2;
    int cont = 0;
    int op, del;
    Calc cal = new Calc();
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDividir = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnNumSete = new javax.swing.JButton();
        btnNumOito = new javax.swing.JButton();
        btnNumNove = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        btnNumQuatro = new javax.swing.JButton();
        btnNumCinco = new javax.swing.JButton();
        btnNumSeis = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnNumUm = new javax.swing.JButton();
        btnNumDois = new javax.swing.JButton();
        btnNumTres = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnNumZero = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        btnSinal = new javax.swing.JButton();
        txtDisplay = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        btnDividir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnBackspace.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBackspace.setText("<-");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLimpar.setText("C");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSubtrair.setText("-");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnNumSete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumSete.setText("7");
        btnNumSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSeteActionPerformed(evt);
            }
        });

        btnNumOito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumOito.setText("8");
        btnNumOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumOitoActionPerformed(evt);
            }
        });

        btnNumNove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumNove.setText("9");
        btnNumNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumNoveActionPerformed(evt);
            }
        });

        btnSomar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSomar.setText("+");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });

        btnNumQuatro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumQuatro.setText("4");
        btnNumQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumQuatroActionPerformed(evt);
            }
        });

        btnNumCinco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumCinco.setText("5");
        btnNumCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCincoActionPerformed(evt);
            }
        });

        btnNumSeis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumSeis.setText("6");
        btnNumSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumSeisActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMultiplicar.setText("*");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnNumUm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumUm.setText("1");
        btnNumUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumUmActionPerformed(evt);
            }
        });

        btnNumDois.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumDois.setText("2");
        btnNumDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumDoisActionPerformed(evt);
            }
        });

        btnNumTres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumTres.setText("3");
        btnNumTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumTresActionPerformed(evt);
            }
        });

        btnIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnNumZero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNumZero.setText("0");
        btnNumZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumZeroActionPerformed(evt);
            }
        });

        btnVirgula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVirgula.setText(".");
        btnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgulaActionPerformed(evt);
            }
        });

        btnSinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSinal.setText("+/-");
        btnSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinalActionPerformed(evt);
            }
        });

        txtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNumSete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumOito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumNove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNumQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNumUm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumDois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnNumTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNumZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumSete, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumOito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumNove, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumUm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumDois, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumTres, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumZero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumZeroActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumZero.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumZero.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumZeroActionPerformed

    private void btnNumCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCincoActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumCinco.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumCinco.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumCincoActionPerformed

    private void btnNumUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumUmActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumUm.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumUm.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumUmActionPerformed

    private void btnNumDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumDoisActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumDois.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumDois.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumDoisActionPerformed

    private void btnNumTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumTresActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumTres.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumTres.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumTresActionPerformed

    private void btnNumQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumQuatroActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumQuatro.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumQuatro.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumQuatroActionPerformed

    private void btnNumSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSeisActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumSeis.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumSeis.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumSeisActionPerformed

    private void btnNumSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumSeteActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumSete.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumSete.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumSeteActionPerformed

    private void btnNumOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumOitoActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumOito.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumOito.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumOitoActionPerformed

    private void btnNumNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumNoveActionPerformed
        
        if (del != 1)
        {
            txtDisplay.setText("");
            del = 1;
        }
        
        String InserirNum = txtDisplay.getText();
        
        if (InserirNum == "") txtDisplay.setText(btnNumNove.getText());
        else {
            InserirNum = txtDisplay.getText() + btnNumNove.getText();
            txtDisplay.setText(InserirNum);
        }
        
    }//GEN-LAST:event_btnNumNoveActionPerformed

    private void btnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVirgulaActionPerformed
        
        if (! txtDisplay.getText().contains(".")) txtDisplay.setText(txtDisplay.getText() + btnVirgula.getText());
        
    }//GEN-LAST:event_btnVirgulaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        txtDisplay.setText("");
        cont = 0;
        del = 1;
        num1 = 0;
        num2 = 0;
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        
        if (txtDisplay.getText().length() > 0) 
        {
            StringBuilder build = new StringBuilder(txtDisplay.getText());
            build.deleteCharAt(txtDisplay.getText().length() - 1);
            txtDisplay.setText(build.toString());
        }
        
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        
        if (cont < 1) {
            cont = 1;
            op = 1;
            num1 = Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText("");
        } else {
            num2 = Double.parseDouble(txtDisplay.getText());
            num1 = cal.Operaçao(num1, num2, op);
            txtDisplay.setText("" + num1);
            op = 1;
            del = 0;
            //JOptionPane.showMessageDialog(this, "num 1: " + num1 + " num 2: " + num2 +" op: " + op);
        }
        
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        
        if (cont < 1) {
            cont = 1;
            op = 2;
            num1 = Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText("");
        } else {
            num2 = Double.parseDouble(txtDisplay.getText());
            num1 = cal.Operaçao(num1, num2, op);
            txtDisplay.setText("" + num1);
            op = 2;
            del = 0;
        }
        
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        
        if (cont < 1) {
            cont = 1;
            op = 3;
            num1 = Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText("");
        } else {
            num2 = Double.parseDouble(txtDisplay.getText());
            num1 = cal.Operaçao(num1, num2, op);
            txtDisplay.setText("" + num1);
            op = 3;
            del = 0;
        }
        
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        
        if (cont < 1) {
            cont = 1;
            op = 4;
            num1 = Double.parseDouble(txtDisplay.getText());
            txtDisplay.setText("");
        } else {
            num2 = Double.parseDouble(txtDisplay.getText());
            num1 = cal.Operaçao(num1, num2, op);
            txtDisplay.setText("" + num1);
            op = 4;
            del = 0;
        }
        
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        
        num2 = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("" + cal.Operaçao(num1, num2, op));
        
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinalActionPerformed
        
        String InserirNum = txtDisplay.getText();
        double trocarSinal;
        
        if (InserirNum != "")
        {
            trocarSinal = Double.parseDouble(txtDisplay.getText());
            trocarSinal *= -1;
            txtDisplay.setText("" + trocarSinal);
        }
        
    }//GEN-LAST:event_btnSinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNumCinco;
    private javax.swing.JButton btnNumDois;
    private javax.swing.JButton btnNumNove;
    private javax.swing.JButton btnNumOito;
    private javax.swing.JButton btnNumQuatro;
    private javax.swing.JButton btnNumSeis;
    private javax.swing.JButton btnNumSete;
    private javax.swing.JButton btnNumTres;
    private javax.swing.JButton btnNumUm;
    private javax.swing.JButton btnNumZero;
    private javax.swing.JButton btnSinal;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JButton btnVirgula;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
