/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerEstoque;
import java.awt.Image;
import java.io.FileInputStream;
import static java.lang.String.valueOf;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Itens;

/**
 *
 * @author giuli
 */
public class FrmAlterarItens extends javax.swing.JFrame {

    private static ControllerEstoque controller = new ControllerEstoque();
    public static FileInputStream fis;
    public static int tam;
    private Image foto;

    /**
     * Creates new form FrmAlterarItens
     */
    public FrmAlterarItens() {
        initComponents();

        if (Itens.cod > 0) {
            txtNome.setText(Itens.nome);
            txtDescricao.setText(Itens.descricao);
            txtQtde.setText(valueOf(Itens.quant));
            txtValor.setText(valueOf(Itens.valorUni));

            try {
                lblImagem.setIcon(new ImageIcon((Image) Itens.imagem));
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnSelecionarI = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(549, 270));
        setPreferredSize(new java.awt.Dimension(549, 270));
        getContentPane().setLayout(null);

        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(226, 36, 77, 16);

        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(226, 82, 77, 16);

        lblQuantidade.setText("Qtde.:");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(226, 124, 37, 16);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar itens final.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(48, 33, 141, 141);

        btnSelecionarI.setText("Selecionar Imagem");
        btnSelecionarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarIActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarI);
        btnSelecionarI.setBounds(48, 192, 141, 23);
        getContentPane().add(txtNome);
        txtNome.setBounds(330, 33, 166, 22);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(330, 79, 166, 22);
        getContentPane().add(txtQtde);
        txtQtde.setBounds(281, 121, 71, 22);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(435, 190, 80, 23);
        getContentPane().add(txtValor);
        txtValor.setBounds(425, 121, 71, 22);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(330, 190, 80, 23);

        lblValor.setText("Valor:");
        getContentPane().add(lblValor);
        lblValor.setBounds(370, 124, 37, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.setMargin(new java.awt.Insets(2, 3, 3, 3));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(225, 190, 80, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarIActionPerformed
        SelecionarImagem();
    }//GEN-LAST:event_btnSelecionarIActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparVariaveis();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparVariaveis();

        txtNome.setText("");
        txtDescricao.setText("");
        txtQtde.setText("");
        txtValor.setText("");

        try {
            lblImagem.setIcon(null);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Itens.quant = Integer.parseInt(txtQtde.getText());
        Itens.nome = txtNome.getText();
        Itens.descricao = txtDescricao.getText();
        Itens.valorUni = Float.parseFloat(txtValor.getText());

        if (Itens.cod > 0) {
            controller.atualizar(2);
        } else {
            controller.salvarItem();
        }

        limparVariaveis();
        Itens.cod = 0;
        FrmEstoque.preencherTabelas();
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAlterarItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAlterarItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSelecionarI;
    private javax.swing.JLabel lblDescricao;
    public static javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void limparVariaveis() {
        Itens.quant = 0;
        Itens.nome = "";
        Itens.descricao = "";
        Itens.valorUni = 0;
        Itens.imagem = null;
    }

    private void SelecionarImagem() {
        JFileChooser jfc = new JFileChooser();

        jfc.setFileFilter(new FileNameExtensionFilter("Arquivo de imagens (*.PNG, *.JPG, *.JPEG)", "png", "jpg", "jpeg"));
        int result = jfc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                fis = new FileInputStream(jfc.getSelectedFile());
                tam = (int) jfc.getSelectedFile().length();
                foto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_SMOOTH);
                lblImagem.setIcon(new ImageIcon(foto));
                lblImagem.updateUI();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
}
