/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import controller.ControllerEstoque;
import java.awt.Image;
import static java.lang.String.valueOf;
import model.estoque;
import java.util.List;
import javax.swing.ImageIcon;
import model.Itens;

/**
 *
 * @author giuli
 */
public class FrmEstoque extends javax.swing.JInternalFrame {

    static ControllerEstoque controller = new ControllerEstoque();
    private static List<estoque> listaItens;

    /**
     * Creates new form FrmPedido
     */
    public FrmEstoque() {
        initComponents();

        preencherTabelas();

        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstoque = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        lblEstoque = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblValorU = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblFotoItem = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(726, 435));
        setMinimumSize(new java.awt.Dimension(726, 435));
        setPreferredSize(new java.awt.Dimension(726, 435));
        getContentPane().setLayout(null);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(520, 380, 110, 23);

        jtEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Nome", "Descrição", "Quantidade ", "Valor Unitário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEstoque);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(49, 48, 615, 190);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(520, 340, 110, 23);

        lblEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstoque.setText("Estoque");
        getContentPane().add(lblEstoque);
        lblEstoque.setBounds(49, 14, 100, 20);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(520, 260, 110, 23);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(520, 300, 110, 23);

        lblValorU.setText("Valor Unitário");
        getContentPane().add(lblValorU);
        lblValorU.setBounds(220, 340, 150, 16);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(360, 230, 230, 190);
        getContentPane().add(lblFotoItem);
        lblFotoItem.setBounds(70, 260, 130, 130);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(220, 260, 150, 16);

        lblQuantidade.setText("Quantidade");
        getContentPane().add(lblQuantidade);
        lblQuantidade.setBounds(220, 300, 150, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        controller.deletarItem(listaItens.get(jtEstoque.getSelectedRow()).codItem);
        preencherTabelas();
        
        lblNome.setText("Nome");
        
        lblQuantidade.setText("Quantidade");
        lblValorU.setText("Valor Unitário");

        try {
            lblFotoItem.setIcon(null);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        new FrmAlterarItens().setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        Itens.cod = listaItens.get(jtEstoque.getSelectedRow()).codItem;
        Itens.quant = listaItens.get(jtEstoque.getSelectedRow()).quant;
        Itens.nome = listaItens.get(jtEstoque.getSelectedRow()).nome;
        Itens.descricao = listaItens.get(jtEstoque.getSelectedRow()).descricao;
        Itens.valorUni = listaItens.get(jtEstoque.getSelectedRow()).valorUni;
        Itens.imagem = listaItens.get(jtEstoque.getSelectedRow()).imagem;
        
        new FrmAlterarItens().setVisible(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jtEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEstoqueMouseClicked
        lblNome.setText(listaItens.get(jtEstoque.getSelectedRow()).nome);
        
        lblQuantidade.setText(valueOf(listaItens.get(jtEstoque.getSelectedRow()).quant));
        lblValorU.setText(valueOf(listaItens.get(jtEstoque.getSelectedRow()).valorUni));

        try {
            lblFotoItem.setIcon(new ImageIcon((Image) listaItens.get(jtEstoque.getSelectedRow()).imagem));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jtEstoqueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtEstoque;
    private javax.swing.JLabel lblEstoque;
    private static javax.swing.JLabel lblFotoItem;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorU;
    // End of variables declaration//GEN-END:variables

    public static void preencherTabelas() {
        DefaultTableModel tabelas = (DefaultTableModel) jtEstoque.getModel();
        tabelas.setNumRows(0);

        listaItens = controller.getUpdateItens();

        Object colunas[] = new Object[5];

        for (int i = 0; i < listaItens.size(); i++) {

            colunas[0] = listaItens.get(i).imagem;
            colunas[1] = listaItens.get(i).nome;
            colunas[2] = listaItens.get(i).descricao;
            colunas[3] = listaItens.get(i).quant;
            colunas[4] = listaItens.get(i).valorUni;

            tabelas.addRow(colunas);
        }
    }
}
