/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.encomendaDados;
import model.modelos;
import model.Itens;
import controller.ControllerEncomendas;
import controller.ControllerModelos;
import controller.ControllerEstoque;

/**
 *
 * @author giuli
 */
public class FrmEncomendar extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEncomendar
     */
    public FrmEncomendar() {
        initComponents();

        lblValorFinal.setText("0,00");
        encomendaDados.tamanho = "XS";
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncomendar = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblTecido = new javax.swing.JLabel();
        btnSelecionarModelo = new javax.swing.JButton();
        btnSelecionarTecido = new javax.swing.JButton();
        lblTamanho = new javax.swing.JLabel();
        cbxTamanho = new javax.swing.JComboBox<>();
        btnInfoTamanho = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        txtTecido = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblImgModelo = new javax.swing.JLabel();
        lblImgTecido = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        setClosable(true);
        setTitle("Encomendar");
        setMaximumSize(new java.awt.Dimension(443, 463));
        setMinimumSize(new java.awt.Dimension(443, 463));
        setPreferredSize(new java.awt.Dimension(443, 463));
        getContentPane().setLayout(null);

        lblEncomendar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEncomendar.setText("Encomendar");
        getContentPane().add(lblEncomendar);
        lblEncomendar.setBounds(30, 40, 90, 20);

        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo);
        lblModelo.setBounds(30, 130, 60, 16);

        lblTecido.setText("Tecido:");
        getContentPane().add(lblTecido);
        lblTecido.setBounds(30, 250, 70, 16);

        btnSelecionarModelo.setText("Selecionar Modelo");
        btnSelecionarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarModeloActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarModelo);
        btnSelecionarModelo.setBounds(270, 140, 140, 23);

        btnSelecionarTecido.setText("Selecionar Tecido");
        btnSelecionarTecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarTecidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionarTecido);
        btnSelecionarTecido.setBounds(270, 270, 140, 23);

        lblTamanho.setText("Tamanho:");
        getContentPane().add(lblTamanho);
        lblTamanho.setBounds(50, 350, 80, 16);

        cbxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL" }));
        cbxTamanho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxTamanhoMouseClicked(evt);
            }
        });
        getContentPane().add(cbxTamanho);
        cbxTamanho.setBounds(110, 350, 50, 22);

        btnInfoTamanho.setText("Recalcular");
        btnInfoTamanho.setMargin(new java.awt.Insets(2, 2, 3, 2));
        btnInfoTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoTamanhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoTamanho);
        btnInfoTamanho.setBounds(170, 350, 80, 23);
        getContentPane().add(txtModelo);
        txtModelo.setBounds(30, 160, 111, 22);
        getContentPane().add(txtTecido);
        txtTecido.setBounds(30, 280, 111, 22);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar);
        btnFinalizar.setBounds(60, 390, 91, 23);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(170, 390, 91, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(280, 390, 91, 23);

        lblValor.setText("Valor:");
        getContentPane().add(lblValor);
        lblValor.setBounds(270, 350, 40, 16);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/encomendar.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(-20, -30, 480, 460);

        lblImgModelo.setMaximumSize(new java.awt.Dimension(100, 94));
        lblImgModelo.setMinimumSize(new java.awt.Dimension(100, 94));
        lblImgModelo.setPreferredSize(new java.awt.Dimension(100, 94));
        lblImgModelo.setRequestFocusEnabled(false);
        getContentPane().add(lblImgModelo);
        lblImgModelo.setBounds(150, 110, 100, 94);

        lblImgTecido.setMaximumSize(new java.awt.Dimension(100, 94));
        lblImgTecido.setMinimumSize(new java.awt.Dimension(100, 94));
        lblImgTecido.setPreferredSize(new java.awt.Dimension(100, 94));
        lblImgTecido.setRequestFocusEnabled(false);
        getContentPane().add(lblImgTecido);
        lblImgTecido.setBounds(150, 250, 100, 94);

        lblValorFinal.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(lblValorFinal);
        lblValorFinal.setBounds(330, 348, 64, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarModeloActionPerformed
        new FrmSelecionarM().setVisible(true);
    }//GEN-LAST:event_btnSelecionarModeloActionPerformed

    private void btnSelecionarTecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarTecidoActionPerformed
        new FrmSelecionarT().setVisible(true);
    }//GEN-LAST:event_btnSelecionarTecidoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (encomendaDados.Modelo == null && encomendaDados.Tecido == null) {
            this.dispose();
        } else {
            if (JOptionPane.showConfirmDialog(this, "Deseja descartar as alterações feitas?", "Cancelar encomenda", YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                LimparEncomenda();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtModelo.setText("");
        try {
            lblImgModelo.setIcon(null);
        } catch (Exception e) {
            System.out.println(e);
        }

        txtTecido.setText("");
        try {
            lblImgTecido.setIcon(null);
        } catch (Exception e) {
            System.out.println(e);
        }

        cbxTamanho.setSelectedItem("XS");

        lblValorFinal.setText("0,00");

        LimparEncomenda();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        ControllerModelos controllerM = new ControllerModelos();
        ControllerEncomendas controllerE = new ControllerEncomendas();

        encomendaDados.tamanho = cbxTamanho.getSelectedItem().toString();
        controllerM.encomendando();
        controllerE.FinalizarEncomenda();

        LimparEncomenda();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void cbxTamanhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTamanhoMouseClicked
        
    }//GEN-LAST:event_cbxTamanhoMouseClicked

    private void btnInfoTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoTamanhoActionPerformed
        encomendaDados.tamanho = cbxTamanho.getSelectedItem().toString();

        if (encomendaDados.Modelo != null && encomendaDados.Tecido != null) {
            CalcularValor();
        }
    }//GEN-LAST:event_btnInfoTamanhoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnInfoTamanho;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSelecionarModelo;
    private javax.swing.JButton btnSelecionarTecido;
    private static javax.swing.JComboBox<String> cbxTamanho;
    private javax.swing.JLabel lblEncomendar;
    private javax.swing.JLabel lblImagem;
    public static javax.swing.JLabel lblImgModelo;
    public static javax.swing.JLabel lblImgTecido;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTecido;
    private javax.swing.JLabel lblValor;
    private static javax.swing.JLabel lblValorFinal;
    public static javax.swing.JTextField txtModelo;
    public static javax.swing.JTextField txtTecido;
    // End of variables declaration//GEN-END:variables

    public static void AtualizarModelo() {

        txtModelo.setText(encomendaDados.Modelo);

        try {
            lblImgModelo.setIcon(new ImageIcon((Image) encomendaDados.imgModelo));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void AtualizarTecido() {

        txtTecido.setText(encomendaDados.Tecido);

        try {
            lblImgTecido.setIcon(new ImageIcon((Image) encomendaDados.imgTecido));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void LimparEncomenda() {
        encomendaDados.Modelo = null;
        encomendaDados.imgModelo = null;
        encomendaDados.Tecido = null;
        encomendaDados.imgTecido = null;
        encomendaDados.tamanho = null;
        encomendaDados.codTecido = -1;
        encomendaDados.quantT = 0;
        encomendaDados.codItens = -1;
    }

    public static void CalcularValor() {
        ControllerEstoque controllerE = new ControllerEstoque();
        controllerE.buscarValorT(encomendaDados.codTecido);
        ControllerModelos controllerM = new ControllerModelos();
        modelos mod = controllerM.valor(cbxTamanho.getSelectedItem().toString());

        float valor = (float) ((mod.tecidoTam * Itens.valorUni) + (mod.horasTrab * 8.16) + 1.3);

        lblValorFinal.setText(String.valueOf(valor));

    }
}
