/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author giuli
 */
public class FrmPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPedido
     */
    public FrmPedido() {
        initComponents();
        
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPedidoImagem = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        btnCancelarPedido = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();
        lblImagem2 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(726, 499));
        setMinimumSize(new java.awt.Dimension(726, 499));
        setPreferredSize(new java.awt.Dimension(726, 499));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "Tipo", "Descrição", "Total", "Concluído", "Retirado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(49, 48, 615, 190);

        lblPedidoImagem.setText("Pedido:");
        getContentPane().add(lblPedidoImagem);
        lblPedidoImagem.setBounds(300, 263, 80, 16);

        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(502, 263, 100, 16);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(153, 154));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 291, 153, 154);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(502, 291, 162, 86);

        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarPedido);
        btnCancelarPedido.setBounds(502, 395, 162, 23);

        lblPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPedido.setText("Pedidos");
        getContentPane().add(lblPedido);
        lblPedido.setBounds(49, 14, 100, 20);

        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedidos 2.png"))); // NOI18N
        getContentPane().add(lblImagem2);
        lblImagem2.setBounds(200, 390, 90, 70);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedidos 1.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(50, 230, 250, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPedidoImagem;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
