/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Point;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author giuli
 */
public class FrmPrincipalF extends javax.swing.JFrame {
 
    /**
     * Creates new form FrmPrincipalC
     */
    public FrmPrincipalF() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDesktop = new javax.swing.JDesktopPane();
        lblImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCadastros = new javax.swing.JMenu();
        mEstoque = new javax.swing.JMenu();
        mPedidos = new javax.swing.JMenu();
        mSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal-removebg-preview.png"))); // NOI18N

        pDesktop.setLayer(lblImagem, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pDesktopLayout = new javax.swing.GroupLayout(pDesktop);
        pDesktop.setLayout(pDesktopLayout);
        pDesktopLayout.setHorizontalGroup(
            pDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDesktopLayout.createSequentialGroup()
                .addGap(0, 422, Short.MAX_VALUE)
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pDesktopLayout.setVerticalGroup(
            pDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDesktopLayout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addComponent(lblImagem))
        );

        mCadastros.setText("Cadastrar Usuários");
        mCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCadastrosMouseClicked(evt);
            }
        });
        mCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastrosActionPerformed(evt);
            }
        });
        jMenuBar1.add(mCadastros);

        mEstoque.setText("Controle de Estoque");
        mEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEstoqueMouseClicked(evt);
            }
        });
        mEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEstoqueActionPerformed(evt);
            }
        });
        jMenuBar1.add(mEstoque);

        mPedidos.setText("Pedidos");
        mPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPedidosMouseClicked(evt);
            }
        });
        mPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPedidosActionPerformed(evt);
            }
        });
        jMenuBar1.add(mPedidos);

        mSair.setText("Sair");
        mSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSairMouseClicked(evt);
            }
        });
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDesktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPedidosActionPerformed
        
    }//GEN-LAST:event_mPedidosActionPerformed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        
    }//GEN-LAST:event_mSairActionPerformed

    private void mSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mSairMouseClicked

    private void mPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPedidosMouseClicked
        FrmPedido pedidos = new FrmPedido();
        pDesktop.add(pedidos);
        Centralizar(pedidos);
        pedidos.show(true);
    }//GEN-LAST:event_mPedidosMouseClicked

    private void mCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastrosActionPerformed
        
    }//GEN-LAST:event_mCadastrosActionPerformed

    private void mCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCadastrosMouseClicked
        FrmCadastroF tela = new FrmCadastroF();
        tela.show();
    }//GEN-LAST:event_mCadastrosMouseClicked

    private void mEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEstoqueActionPerformed
        
    }//GEN-LAST:event_mEstoqueActionPerformed

    private void mEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEstoqueMouseClicked
        FrmEstoque estoque = new FrmEstoque();
        pDesktop.add(estoque);
        Centralizar(estoque);
        estoque.show(true);
    }//GEN-LAST:event_mEstoqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipalF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipalF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImagem;
    public javax.swing.JMenu mCadastros;
    private javax.swing.JMenu mEstoque;
    private javax.swing.JMenu mPedidos;
    private javax.swing.JMenu mSair;
    private javax.swing.JDesktopPane pDesktop;
    // End of variables declaration//GEN-END:variables

    public static void Centralizar(JInternalFrame internalFrame) {

        JDesktopPane desktopPane = internalFrame.getDesktopPane();

        int desktopWidth = desktopPane.getWidth();
        int desktopHeight = desktopPane.getHeight();
        int frameWidth = internalFrame.getWidth();
        int frameHeight = internalFrame.getHeight();

        Point newLocation = new Point((desktopWidth - frameWidth) / 2, (desktopHeight - frameHeight) / 2);

        internalFrame.setLocation(newLocation);
    }
    
}
