/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import model.modelos;
import model.encomendaDados;
import java.util.List;
import controller.ControllerModelos;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author giuli
 */
public class FrmSelecionarM extends javax.swing.JFrame {
    
    private static ControllerModelos controller = new ControllerModelos();
    public static List <modelos> listaModelos;
    public static int num;
    
    public static String filtro;

    /**
     * Creates new form FrmSelecionarM
     */
    public FrmSelecionarM() {
        initComponents();
        preencherTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxFiltro = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtModelos = new javax.swing.JTable();
        txtModelo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSelecionarModelo = new javax.swing.JLabel();
        lblMolde = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblFotoModelo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(563, 482));
        getContentPane().setLayout(null);

        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--", "Saia", "Calça", "Camisa", "Vestido", "Blusa", "Short", "Tudo" }));
        cbxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFiltroActionPerformed(evt);
            }
        });
        getContentPane().add(cbxFiltro);
        cbxFiltro.setBounds(300, 40, 110, 22);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar);
        btnFiltrar.setBounds(430, 40, 72, 23);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jtModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Foto", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtModelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtModelos);
        if (jtModelos.getColumnModel().getColumnCount() > 0) {
            jtModelos.getColumnModel().getColumn(0).setHeaderValue("Foto");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(34, 73, 475, 158);

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo);
        txtModelo.setBounds(130, 270, 160, 22);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(70, 320, 90, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(70, 360, 90, 23);

        lblSelecionarModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelecionarModelo.setText("Selecionar Modelo");
        getContentPane().add(lblSelecionarModelo);
        lblSelecionarModelo.setBounds(70, 13, 180, 20);

        lblMolde.setText("Modelo:");
        getContentPane().add(lblMolde);
        lblMolde.setBounds(70, 270, 60, 16);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esboço.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(190, 250, 190, 340);

        lblFotoModelo.setBackground(new java.awt.Color(204, 255, 204));
        lblFotoModelo.setMaximumSize(new java.awt.Dimension(174, 174));
        lblFotoModelo.setMinimumSize(new java.awt.Dimension(174, 174));
        lblFotoModelo.setPreferredSize(new java.awt.Dimension(174, 174));
        getContentPane().add(lblFotoModelo);
        lblFotoModelo.setBounds(340, 250, 174, 174);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (jtModelos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um modelo.");
        } else {
            num = jtModelos.getSelectedRow();
            Atualizar();
            FrmEncomendar.AtualizarModelo();
            if (encomendaDados.Modelo != null && encomendaDados.Tecido != null) {
                FrmEncomendar.CalcularValor();
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jtModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtModelosMouseClicked
        txtModelo.setText(listaModelos.get(jtModelos.getSelectedRow()).molde);
        
        try {
            lblFotoModelo.setIcon(new ImageIcon(listaModelos.get(jtModelos.getSelectedRow()).imagem));            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jtModelosMouseClicked

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtro = "'%" + cbxFiltro.getSelectedItem().toString() + "%'";
        
        switch (filtro) {
            case "'--Selecionar--'" -> JOptionPane.showMessageDialog(this, "Selecione um filtro.");
            case "'Tudo'" -> preencherTabelas();
            default -> preencherTabelasFiltro(filtro);
        }
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void cbxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSelecionarM().setVisible(true);                
            }
        });
    }
    private static void preencherTabelas (){
        DefaultTableModel tabelas = (DefaultTableModel) jtModelos.getModel();
        tabelas.setNumRows(0);
        
        List <modelos> listaModelo = controller.getUpdateModelos();
                
        Object colunas[] = new Object[2];
                
        for (int i = 0; i < listaModelo.size(); i++) {
                                   
            colunas[0] = listaModelo.get(i).imagem;
            colunas[1] = listaModelo.get(i).molde;
            
            tabelas.addRow(colunas);
        }
        listaModelos = listaModelo;
    }
    
    private static void preencherTabelasFiltro (String filtro){
        DefaultTableModel tabelas = (DefaultTableModel) jtModelos.getModel();
        tabelas.setNumRows(0);
        
        List <modelos> listaModelo = controller.getFiltrarModelos(filtro);
                
        Object colunas[] = new Object[2];
                
        for (int i = 0; i < listaModelo.size(); i++) {
                                   
            colunas[0] = listaModelo.get(i).imagem;
            colunas[1] = listaModelo.get(i).molde;
            
            tabelas.addRow(colunas);
        }
        
        listaModelos = listaModelo;
    }
    
    private static void Atualizar(){ //fazer um get nas telas de selecionar e passar para a variável static em encomendas
        encomendaDados.Modelo = listaModelos.get(num).molde;
        encomendaDados.codItens = listaModelos.get(num).codMateriais;
        
        try {
            encomendaDados.imgModelo = listaModelos.get(num).imagem;            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtModelos;
    private javax.swing.JLabel lblFotoModelo;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblMolde;
    private javax.swing.JLabel lblSelecionarModelo;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
