/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerEstoque;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.encomendaDados;
import model.estoque;

/**
 *
 * @author giuli
 */
public class FrmSelecionarT extends javax.swing.JFrame {

    static ControllerEstoque controller = new ControllerEstoque();
    static List<estoque> listaTecidos;

    /**
     * Creates new form FrmSelecionarT
     */
    public FrmSelecionarT() {
        initComponents();
        preencherTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelecionarTecido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTecidos = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JButton();
        lblFotoTecido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(562, 301));
        getContentPane().setLayout(null);

        lblSelecionarTecido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelecionarTecido.setText("Selecionar Tecido");
        getContentPane().add(lblSelecionarTecido);
        lblSelecionarTecido.setBounds(73, 12, 210, 20);

        jtTecidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Foto", "Tecido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTecidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTecidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTecidos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(47, 40, 255, 154);

        btnSelecionar.setText("Selecionar");
        btnSelecionar.setMargin(new java.awt.Insets(2, 3, 3, 3));
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionar);
        btnSelecionar.setBounds(120, 210, 110, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(340, 212, 85, 23);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tecido.png"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(340, 0, 250, 240);

        btnCancelar1.setText("Cancelar");
        getContentPane().add(btnCancelar1);
        btnCancelar1.setBounds(340, 212, 85, 23);
        getContentPane().add(lblFotoTecido);
        lblFotoTecido.setBounds(340, 40, 154, 154);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (jtTecidos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Tecido.");
        } else {
            Atualizar(jtTecidos.getSelectedRow());
            FrmEncomendar.AtualizarTecido();
            if (encomendaDados.Modelo != null && encomendaDados.Tecido != null) {
                FrmEncomendar.CalcularValor();
            }
            this.dispose();
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtTecidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTecidosMouseClicked
        try {
            lblFotoTecido.setIcon(new ImageIcon((Image) listaTecidos.get(jtTecidos.getSelectedRow()).imagem));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jtTecidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSelecionarT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSelecionarT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtTecidos;
    public static javax.swing.JLabel lblFotoTecido;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblSelecionarTecido;
    // End of variables declaration//GEN-END:variables

    public static void preencherTabelas() {
        DefaultTableModel tabelas = (DefaultTableModel) jtTecidos.getModel();
        tabelas.setNumRows(0);

        listaTecidos = controller.getFiltrarI("'%tecido%'");
        estoque item = new estoque();

        Object colunas[] = new Object[2];

        for (int i = 0; i < listaTecidos.size(); i++) {
            item = listaTecidos.get(i);

            colunas[0] = item.imagem;
            colunas[1] = item.nome;

            tabelas.addRow(colunas);
        }
    }

    private static void Atualizar(int tupla) { //fazer um get nas telas de selecionar e passar para a variável static em encomendas

        encomendaDados.Tecido = listaTecidos.get(tupla).nome;
        encomendaDados.codTecido = listaTecidos.get(tupla).codItem;

        try {
            encomendaDados.imgTecido = listaTecidos.get(tupla).imagem;
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
